Game dev - game system
sharpstorm/pekoland pull request #40
Opened 2021-06-17 11:42 UTC by bamboolord

2021-06-17 12:13 UTC, sharpstorm requested changes
Many problems

2021-06-17 12:13 UTC, sharpstorm commented on game/workers/asset-loader.js
> +    const load3 = loadAsset(['Images/template1_collision.png', 'Images/template1_collision.png'])
File Wrong

2021-06-17 12:13 UTC, sharpstorm commented on game/ui/ui-game.js
> +import GameManager from '../managers/game-manager.js';
Should change to attach click listener instead. Game Manager only used once, can further separate elements

2021-06-17 12:13 UTC, sharpstorm commented on game/net/server/game-data-sender.js
> +  'gameLobby-echo': buildGameLobbyUpdate,
Need to normalise OpCode

2021-06-17 12:13 UTC, sharpstorm commented on game/net/server/game-data-handler.js
> +  'gameLobby': handleGameLobby,
Normalise OpCode

2021-06-17 12:13 UTC, sharpstorm commented on game/net/server/game-data-handler.js
> +// eslint-disable-next-line no-unused-vars
Need to change how packet handling is done here - Too many subcommands under a single opcode

2021-06-17 12:13 UTC, sharpstorm commented on game/net/server/game-data-handler.js
> +  CheckersGame.getInstance().checkersMove(data);
Need to generalise

2021-06-17 12:13 UTC, sharpstorm commented on game/net/client/game-data-sender.js
> +  'gameLobby': buildGameLobbyUpdate,
Normalise OpCode

2021-06-17 12:13 UTC, sharpstorm commented on game/net/client/game-data-handler.js
> +  'gameLobby-echo': handleGameLobby,
Normalise OpCode

2021-06-17 12:13 UTC, sharpstorm commented on game/net/client/game-data-handler.js
> +function handleGameLobby(data, conn) {
Very Messy need to tidy up

2021-06-17 12:13 UTC, sharpstorm commented on game/net/client/game-data-handler.js
> +  CheckersGame.getInstance().checkersMove(data);
Need to Generalise

2021-06-17 12:13 UTC, sharpstorm commented on game/models/map.js
> +  getFuniture(x, y) {
Spelling

2021-06-17 12:13 UTC, sharpstorm commented on game/models/map.js
> +  getFuniture(x, y) {
Why not do this during initialization where collision is processed

2021-06-17 12:13 UTC, sharpstorm commented on game/models/map.js
> +    document.addEventListener('click', this.getColor);
No Modifying DOM in Models

2021-06-17 12:13 UTC, sharpstorm commented on game/managers/world-manager.js
> +    this.gameLobbies = {};
Lobby system is coded to checkers. Should be the other way round

2021-06-17 12:13 UTC, sharpstorm commented on game/managers/game-manager.js
> +    /* GAME STATES
Make this list into enum

2021-06-17 12:13 UTC, sharpstorm commented on game/managers/game-manager.js
> +  getGame(gameName) {
Use Lambda Find

2021-06-17 12:13 UTC, sharpstorm commented on game/managers/game-manager.js
> +
Should change ConstructorName, not advisable to use

2021-06-17 12:13 UTC, sharpstorm commented on game/managers/animation-manager.js
> +  register(game) {
Design: Game layer drawables should be independent of GameManager --> Possible to remove GameManager import

2021-06-17 13:01 UTC, sharpstorm commented on game/managers/world-manager.js
> +    this.gameLobbies = {};
Generalised Lobby System

2021-06-17 13:06 UTC, bamboolord commented on game/net/server/game-data-sender.js
> +  'gameLobby-echo': buildGameLobbyUpdate,
fixed

2021-06-17 13:06 UTC, bamboolord commented on game/net/server/game-data-handler.js
> +  'gameLobby': handleGameLobby,
fixed

2021-06-18 13:53 UTC, sharpstorm approved these changes
Issues Resolved

2021-06-18 13:59 UTC, merged